# Generated by Django 4.0 on 2021-12-18 07:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_moviegenre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviegenre',
            name='movie',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='genres', to='movie.movie'),
        ),
    ]
